#!/bin/bash

##############################################
##       Author: Gïng Pepper       ##
##     https://experibassmusic.eth.limo     ##
##############################################

STEP=5       # Step Up/Down brightnes by: 5 = ".05", 10 = ".10", etc.

notify() {
	value=$(xbacklight -get)
    dunstify -t 2000 "Display brightness: ${value}" -h string:x-dunst-stack-tag:display_brightness
}
if [[ $1 == [uU][pP] ]] ; then
    xbacklight -inc $STEP -steps $STEP
    notify
else
    xbacklight -dec $STEP -steps $STEP
    notify
fi
